### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/beegfs#5]
### Page URL

https://docs.netapp.com/us-en/beegfs/beegfs-deploy-bestpractice.html

### Page title

Review best practices

### Summary

This link is broken, returns 404.

![image](https://github.com/NetAppDocs/beegfs/assets/56453501/8614c6e2-4fe2-4126-9bf1-55d121155379)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by scaleoutsean** [comment]
Why is this still open 1 year later?

**Comment by ntap-bmegan** [comment]
@netapp-jsnyder - The link is still broken. 

Source: `link:beegfs-deploy-beegfs-general-config.html[Create the Ansible inventory]`

Possible target based on [site search](https://docs.netapp.com/us-en/beegfs/beegfs-deploy-create-inventory.html?q=create+ansible+inventory): `beegfs-deploy-create-inventory.html` (title is "Create the Ansible inventory")

Other files with `ansible` in the file name:

![image](https://github.com/NetAppDocs/beegfs/assets/56453501/480517bb-7660-4ef7-9bec-b67f291a4261)
